# Generated by Django 3.2.19 on 2023-06-17 12:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('bat_name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'batiments',
            },
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'cantons',
            },
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('pistes_nam', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'pistes',
            },
        ),
        migrations.CreateModel(
            name='Remontee',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('rems_name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'remontees',
            },
        ),
        migrations.CreateModel(
            name='PisteLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarnsformed_geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('length', models.FloatField()),
                ('piste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swissgeo.piste')),
            ],
            options={
                'db_table': 'piste_lengths',
            },
        ),
    ]
