# Generated by Django 3.2.19 on 2023-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canton',
        ),
        migrations.AddField(
            model_name='piste',
            name='difficulty',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='PisteLength',
        ),
    ]
