# Generated by Django 3.2.19 on 2023-06-16 12:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('bat_name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'batiments',
            },
        ),
    ]
