# Generated by Django 3.2.19 on 2023-06-17 07:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swissgeo', '0002_batiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PisteLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarnsformed_geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('length', models.FloatField()),
                ('piste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swissgeo.piste')),
            ],
            options={
                'db_table': 'piste_lengths',
            },
        ),
    ]
